apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iatc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-psdg-tenant/rhtap-demo-app/hacbs-test-project-iatc@sha256:ed430db0ed9d5026248c0fbf05936d265a9e27d7d2e8b54218da2d94d7370f34
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
