apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iatc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iatc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iatc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iatc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iatc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-psdg-tenant/rhtap-demo-app/hacbs-test-project-iatc@sha256:5b5a3c136be6d4e323c27c994cab92c33e74a6eedc7a98abddfc411c1dfc1579
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
